festival:
    - name
artist:
    - firstname
    - lastname
    - pseudo
type:
    - key
hotel:
    - name
ticket:
    - name
links:
    festival:
        Le Big festival:
            artist:
                - selah sue
                - Iggy Pop
                - Skip the Use
                - JoeyStarr
                - Brigitte
                - Shaka Ponk
            type:
                - electro
                - rock
                - pop
                - hip-hop
                - reggae
            hotel:
                - hotel9
                - hotel10
                - hotel11
                - hotel12
            ticket:
                - ticket9
                - ticket10
                - ticket11
        Festival de Nîmes:
            artist:
                - Lionel Richie
                - David Bowie
                - Depeche Mode
                - Placebo
            type:
                - electro
                - rock
                - pop
                - reggae
                - hip-hop
            hotel:
                - hotel25
                - hotel26
                - hotel27
                - hotel28
        Les Vieilles Charrues:
            artist:
                - deep purple
                - New Order
                - Arcade Fire
                - Lionel Richie
                - London Grammar
                - David Guetta
            type:
                - electro
                - rock
                - pop
                - hip-hop
            hotel:
                - hotel1
                - hotel2
                - hotel3
                - hotel4
            ticket:
                - ticket1
                - ticket2
                - ticket3
                - ticket4
        Les Déferlantes:
            artist:
                - fauve
                - blondie
                - UB40
                - Lenny Kravitz
                - Calogero
                - Brigitte
                - Carlos Santana
            type:
                - electro
                - rock
                - hip-hop
                - pop
                - reggae
            hotel:
                - hotel33
                - hotel34
                - hotel35
                - hotel36
            ticket:
                - ticket28
                - ticket29
                - ticket30
        Main Square:
            artist:
                - Lilly Wood and the Prick
                - The Black Keys
                - stromae
                - Pharrell Williams
                - Coldplay
                - London Grammar
                - Depeche Mode
                - Lenny Kravitz
                - Placebo
                - Shaka Ponk
            type:
                - electro
                - rock
                - pop
                - hip-hop
                - reggae
            hotel:
                - hotel13
                - hotel14
                - hotel15
                - hotel16
            ticket:
                - ticket12
                - ticket13
                - ticket14
                - ticket15
        Festival Musilac:
            artist:
                - cerrone
                - Muse
                - alt-J
                - David Guetta
            type:
                - electro
                - rock
                - pop
                - reggae
                - blues
            hotel:
                - hotel21
                - hotel22
                - hotel23
                - hotel24
            ticket:
                - ticket22
                - ticket23
                - ticket24
        Festival Les Femmes s'en Mêlent:
            artist:
                - Yelle
                - M.I.A.
                - Ebony Bones
                - Brigitte
            type:
                - electro
                - rock
                - pop
                - reggae
                - blues
            hotel:
                - hotel29
                - hotel30
                - hotel31
                - hotel32
            ticket:
                - ticket25
                - ticket26
                - ticket27
        CosmoJazz Festival:
            artist:
                - andré manoukian
            type:
                - jazz
            hotel:
                - hotel5
                - hotel6
                - hotel7
                - hotel8
            ticket:
                - ticket5
                - ticket6
                - ticket7
                - ticket8
        Les Francofolies:
            artist:
                - Veronique Sanson
                - Christine and the Queens
                - Florent Pagny
                - Fréro Delavega
            type:
                - electro
                - rock
                - pop
                - reggae
            hotel:
                - hotel17
                - hotel18
                - hotel19
                - hotel20
            ticket:
                - ticket16
                - ticket17
                - ticket18
        hellfest:
            artist:
                - scorpions
                - faith no more
                - slash
                - marilyn manson
            type:
                - metal
                - rock
        solidays:
            artist:
                - asaf avidan
                - moriarty
                - faada freddy
            type:
                - electro
                - rock
                - pop
                - hip-hop
                - reggae
                - variete
    artist:
        selah sue:
            festival:
                - Le Big festival
        deep purple:
            festival:
                - Les Vieilles Charrues
        fauve:
            festival:
                - Les Déferlantes
        Lilly Wood and the Prick:
            festival:
                - Main Square
        The Black Keys:
            festival:
                - Main Square
        New Order:
            festival:
                - Les Vieilles Charrues
        blondie:
            festival:
                - Les Déferlantes
        stromae:
            festival:
                - Main Square
        cerrone:
            festival:
                - Festival Musilac
        Muse:
            festival:
                - Festival Musilac
        Yelle:
            festival:
                - Festival Les Femmes s'en Mêlent
        UB40:
            festival:
                - Les Déferlantes
        Iggy Pop:
            festival:
                - Le Big festival
        alt-J:
            festival:
                - Festival Musilac
        andré manoukian:
            festival:
                - CosmoJazz Festival
        M.I.A.:
            festival:
                - Festival Les Femmes s'en Mêlent
        Ebony Bones:
            festival:
                - Festival Les Femmes s'en Mêlent
        Arcade Fire:
            festival:
                - Les Vieilles Charrues
        Pharrell Williams:
            festival:
                - Main Square
        Skip the Use:
            festival:
                - Le Big festival
        Coldplay:
            festival:
                - Main Square
        JoeyStarr:
            festival:
                - Le Big festival
        Lionel Richie:
            festival:
                - Festival de Nîmes
                - Les Vieilles Charrues
        David Bowie:
            festival:
                - Festival de Nîmes
        London Grammar:
            festival:
                - Les Vieilles Charrues
                - Main Square
        Depeche Mode:
            festival:
                - Festival de Nîmes
                - Main Square
        Veronique Sanson:
            festival:
                - Les Francofolies
        Christine and the Queens:
            festival:
                - Les Francofolies
        Lenny Kravitz:
            festival:
                - Les Déferlantes
                - Main Square
        Placebo:
            festival:
                - Festival de Nîmes
                - Main Square
        Florent Pagny:
            festival:
                - Les Francofolies
        Calogero:
            festival:
                - Les Déferlantes
        Brigitte:
            festival:
                - Les Déferlantes
                - Le Big festival
                - Festival Les Femmes s'en Mêlent
        Fréro Delavega:
            festival:
                - Les Francofolies
        David Guetta:
            festival:
                - Les Vieilles Charrues
                - Festival Musilac
        Carlos Santana:
            festival:
                - Les Déferlantes
        Shaka Ponk:
            festival:
                - Main Square
                - Le Big festival
        scorpions:
            festival:
                - hellfest
        faith no more:
            festival:
                - hellfest
        slash:
            festival:
                - hellfest
        marilyn manson:
            festival:
                - hellfest
        asaf avidan:
            festival:
                - solidays
        moriarty:
            festival:
                - solidays
        faada freddy:
            festival:
                - solidays
