festival:
    - name
artist:
    - firstname
    - lastname
links:
    # festival:
    #     sziget:
    #         artist:
    #             - macklemore
    # artist:
    #     macklemore:
    #         festival:
    #             - sziget