login_oauth:
    pattern: /login/{provider}
    defaults: { _controller: FestitimeUserBundle:User:loginOauth }

login:
    pattern: /login
    defaults: { _controller: FestitimeUserBundle:User:login }

#google_login:
#    pattern: /login/google

logout:
    pattern: /logout
    defaults: { _controller: FestitimeUserBundle:User:logout }

postUser:
    path: /users/register
    defaults: { _controller: FestitimeUserBundle:User:postUser }
    requirements:
        _method: POST

postUserConnect:
    path: /users/connect
    defaults: { _controller: FestitimeUserBundle:User:postUserConnect }
    requirements:
        _method: POST

# After payment, Paypal call paymentStatus
paymentStatus:
    path: /payment/status
    defaults: { _controller: FestitimeUserBundle:User:paymentStatus }

payment:
    path: /payment
    defaults: { _controller: FestitimeUserBundle:User:payment }
    requirements:
        _method: POST

testFlashBag:
    path: /test123
    defaults: { _controller: FestitimeUserBundle:User:test }

users:
    type: rest
    resource: Festitime\bundles\UserBundle\Controller\UserApiController
