login_oauth:
    pattern: /login/{provider}
    defaults: { _controller: FestitimeUserBundle:User:loginOauth }

login:
    pattern: /login
    defaults: { _controller: FestitimeUserBundle:User:login }

#google_login:
#    pattern: /login/google

logout:
    pattern: /logout
    defaults: { _controller: FestitimeUserBundle:User:logout }

postUser:
    path: /users/register
    defaults: { _controller: FestitimeUserBundle:User:postUser }
    requirements:
        _method: POST

postUserConnect:
    path: /users/connect
    defaults: { _controller: FestitimeUserBundle:User:postUserConnect }
    requirements:
        _method: POST

users:
    type: rest
    resource: Festitime\bundles\UserBundle\Controller\UserApiController
