parameters:
    festitime.user_service.class: Festitime\bundles\UserBundle\Services\UserService

services:
    festitime.user_service:
        class: %festitime.user_service.class%
        arguments: [@request_stack, @doctrine_mongodb]

