festitime_database:
    resource: "@FestitimeDatabaseBundle/Resources/config/routing.yml"
    prefix:   /

festitime_user:
    resource: "@FestitimeUserBundle/Resources/config/routing.yml"
    prefix:   /

festitime_festival:
    resource: "@FestitimeFestivalBundle/Resources/config/routing.yml"
    prefix:   /

