#Payum routes are for PayumBundle
payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_authorize:
    resource: "@PayumBundle/Resources/config/routing/authorize.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

festitime_artist:
    resource: "@FestitimeArtistBundle/Resources/config/routing.yml"
    prefix:   /

festitime_database:
    resource: "@FestitimeDatabaseBundle/Resources/config/routing.yml"
    prefix:   /

festitime_user:
    resource: "@FestitimeUserBundle/Resources/config/routing.yml"
    prefix:   /

festitime_festival:
    resource: "@FestitimeFestivalBundle/Resources/config/routing.yml"
    prefix:   /

