festitime_connection:
    resource: "@FestitimeConnectionBundle/Resources/config/routing.yml"
    prefix:   /

festitime_festival:
    resource: "@FestitimeFestivalBundle/Resources/config/routing.yml"
    prefix:   /

