Festitime\bundles\FestivalBundle\Document\Festival:
    fields:
        id:
            id: true
        name:
            type: string
        description:
            type: string
        type:
            type: collection
        img:
            type: string
        start_date:
            type: date
        end_date:
            type: date
        city:
            type: string
        region:
            type: string
        country:
            type: string
        price:
            type: int
