Festitime\DatabaseBundle\Document\Artist:
    type: document
    repositoryClass: Festitime\DatabaseBundle\Repository\ArtistRepository
    referenceMany:
        festivals:
            targetDocument: Festitime\DatabaseBundle\Document\Festival
    fields:
        id:
            id: true
        pseudo:
            type: string
        firstname:
            type: string
        lastname:
            type: string
        description:
            type: string
        type:
            type: collection
        picture:
            type: string
        pictures:
            type: collection
