Festitime\DatabaseBundle\Document\FestivalArtists:
    type: document
    repositoryClass: Festitime\DatabaseBundle\Repository\FestivalArtistsRepository
    referenceOne:
        festival:
            targetDocument: Festitime\DatabaseBundle\Document\Festival
        artist:
            targetDocument: Festitime\DatabaseBundle\Document\Artist
    fields:
        id:
            id: true
