Festitime\DatabaseBundle\Document\Festival:
    type: document
    repositoryClass: Festitime\DatabaseBundle\Repository\FestivalRepository
    referenceMany:
        festival_artists:
            targetDocument: Festitime\DatabaseBundle\Document\FestivalArtists
    fields:
        id:
            id: true
        name:
            type: string
        description:
            type: string
        type:
            type: collection
        img:
            type: string
        start_date:
            gedmo:
                timestampable:
                on: create
            type: date
        end_date:
            type: date
            gedmo:
                timestampable:
                on: change
        city:
            type: string
        region:
            type: string
        country:
            type: string
        price:
            type: int
