Festitime\DatabaseBundle\Document\Festival:
    type: document
    repositoryClass: Festitime\DatabaseBundle\Repository\FestivalRepository
    referenceMany:
        artists:
            targetDocument: Festitime\DatabaseBundle\Document\Artist
        type:
            targetDocument: Festitime\DatabaseBundle\Document\Type
        hotels:
            targetDocument: Festitime\DatabaseBundle\Document\Hotel
        tickets:
            targetDocument: Festitime\DatabaseBundle\Document\Ticket
    fields:
        id:
            id: true
        name:
            type: string
        description:
            type: string
        img:
            type: string
        pictures:
            type: collection
        start_date:
            gedmo:
                timestampable:
                on: create
            type: date
        end_date:
            type: date
            gedmo:
                timestampable:
                on: change
        city:
            type: string
        region:
            type: string
        country:
            type: string
        price:
            type: int
