Festitime\DatabaseBundle\Document\Ticket:
    type: document
    repositoryClass: Festitime\DatabaseBundle\Repository\TicketRepository
    fields:
        id:
            id: true
        name:
            type: string
        price:
            type: int
