<?php

namespace Festitime\DatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends DocumentRepository
{
    public function getArtists($limit)
    {
        $artists = $this->dm->createQueryBuilder('FestitimeDatabaseBundle:Artist')
            ->limit($limit)
            ->hydrate()
            ->getQuery()
            ->execute()
        ;

        return $artists->toArray();
    }
}
