<?php

namespace Festitime\DatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * FestivalArtistsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivalArtistsRepository extends DocumentRepository
{
}