<?php

namespace Festitime\DatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * FestivalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivalRepository extends DocumentRepository
{
    public function getFestivals($limit)
    {
        $festivals = $this->dm->createQueryBuilder('FestitimeDatabaseBundle:Festival')
            ->limit($limit)
            ->hydrate()
            ->getQuery()
            ->execute()
        ;

        return $festivals->toArray();
    }
}