<?php

namespace Festitime\DatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends DocumentRepository
{
}