home:
    path: /
    defaults: { _controller: FestitimeFestivalBundle:Festival:home }

index:
    path: /home
    defaults: { _controller: FestitimeFestivalBundle:Festival:index }

postFestival:
    path: /festivals/new
    defaults: { _controller: FestitimeFestivalBundle:Festival:postFestival }
    requirements:
        _method: POST

putFestival:
    path: /festivals/{id}
    defaults: { _controller: FestitimeFestivalBundle:Festival:putFestival }
    requirements:
        _method: PUT

festivals:
    type: rest
    resource: Festitime\Bundles\FestivalBundle\Controller\FestivalApiController
