index:
    path: /
    defaults: { _controller: FestitimeFestivalBundle:Festival:index }

home:
    path: /home
    defaults: { _controller: FestitimeFestivalBundle:Festival:home }

postFestival:
    path: /festivals/new
    defaults: { _controller: FestitimeFestivalBundle:Festival:postFestival }
    requirements:
        _method: POST

getFestivals:
    path: /festivals
    defaults: { _controller: FestitimeFestivalBundle:Festival:getFestivals }
    #requirements:
    #    _method: POST
