newHoome:
    path: /home
    defaults: { _controller: FestitimeFestivalBundle:Festival:newHome }

home:
    path: /
    defaults: { _controller: FestitimeFestivalBundle:Festival:index }

adminFestivals:
    path: /festivals/admin
    defaults: { _controller: FestitimeFestivalBundle:Festival:admin }

postFestival:
    path: /festivals/new
    defaults: { _controller: FestitimeFestivalBundle:Festival:postFestival }
    requirements:
        _method: POST

festivals:
    type: rest
    resource: Festitime\bundles\FestivalBundle\Controller\FestivalApiController
