home:
    path: /
    defaults: { _controller: FestitimeFestivalBundle:Festival:home }

index:
    path: /home
    defaults: { _controller: FestitimeFestivalBundle:Festival:index }

postFestival:
    path: /festivals/new
    defaults: { _controller: FestitimeFestivalBundle:Festival:postFestival }
    requirements:
        _method: POST

getFestivals:
    path: /festivals
    defaults: { _controller: FestitimeFestivalBundle:Festival:getFestivals }
    #requirements:
    #    _method: POST

deleteFestival:
    path: /festivals/{id}
    defaults: { _controller: FestitimeFestivalBundle:Festival:deleteFestival }
    requirements:
        _method: DELETE
